/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax_2.vistas;

import javax.swing.JOptionPane;
import provemax_2.accesoDatos.ProductoData;
import provemax_2.entidades.Producto;

/**
 *
 * @author Usuario
 */
public class Productos extends javax.swing.JInternalFrame {


    private ProductoData producData= new ProductoData();
    private Producto productoActual= null; 
    
    
    
    
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jlRegistroProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtCodigoProducto = new javax.swing.JTextField();
        jtNombreProducto = new javax.swing.JTextField();
        jtDescripcionProducto = new javax.swing.JTextField();
        jtPrecioProducto = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();
        jcEstado = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtStockMinimo = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(219, 247, 194));
        jPanel1.setAlignmentX(0.5F);
        jPanel1.setAlignmentY(0.5F);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        jbModificar.setText("Modificar");
        jPanel1.add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lupa-30.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jlRegistroProductos.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jlRegistroProductos.setText("REGISTRO DE PRODUCTOS");
        jPanel1.add(jlRegistroProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel1.setText("CODIGO PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setText("NOMBRE PRODUCTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("DESCRIPCION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("PRECIO ACTUAL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel1.add(jtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, -1));
        jPanel1.add(jtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 80, 250, -1));
        jPanel1.add(jtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 120, 270, -1));
        jPanel1.add(jtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 160, 270, -1));

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-50.png"))); // NOI18N
        jbEliminar.setText("Elimininar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 130, 40));

        jcEstado.setText("Estado");
        jPanel1.add(jcEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setText("STOCK");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(jtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 110, -1));

        jLabel6.setText("STOCK MINIMO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jPanel1.add(jtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
      
        try{
            Integer idProducto=Integer.parseInt(jtCodigoProducto.getText());
        
        productoActual=producData.buscarProductoPorId(idProducto);
        if(productoActual!=null){
            
            
            jtNombreProducto.setText(productoActual.getNombreProducto());
            jtDescripcionProducto.setText(productoActual.getDescripcion());
            
            jtPrecioProducto.setText(String.valueOf(productoActual.getPrecioActual()));
             
            jtStock.setText(String.valueOf(productoActual.getStock()));
            
            jtStockMinimo.setText(String.valueOf(productoActual.getStockMinimo()));
            
            jcEstado.setSelected(productoActual.isEstado());
        }
        }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null,"Debe ingresar un numero valido");
            
          
            
         
        }}
        
    
    
    
    
//    try{
//            Integer idProducto=Integer.parseInt(jtCodigoProducto.getText());
//        
//        productoActual=producData.buscarProductoPorId(idProducto);
//        if(productoActual!=null){
//            
//            
//            jtNombreProducto.setText(productoActual.getNombreProducto());
//            jtDescripcionProducto.setText(productoActual.getDescripcion());
//            
//            jtPrecioProducto.setText(String.valueOf(productoActual.getPrecioActual()));
//             
//            jtStock.setText(String.valueOf(productoActual.getStock()));
//            
//            jtStockMinimo.setText(String.valueOf(productoActual.getStockMinimo()));
//            
//            jcEstado.setSelected(productoActual.isEstado());
//        }
//        }catch(NumberFormatException ex){
//                JOptionPane.showMessageDialog(null,"Debe ingresar un numero valido");
//}
        private void limpiarCampos(){
            
        
        jtDescripcionProducto.setText("");
        jtNombreProducto.setText("");
        jtPrecioProducto.setText("");
        jtStock.setText("");
        jtStockMinimo.setText("");
        jcEstado.setSelected(true);
        
    
      
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed

      limpiarCampos();
      productoActual=null;

    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed


        String nombreProducto=jtNombreProducto.getText();
        String descripcion=jtDescripcionProducto.getText();
        double precioActual = Double.parseDouble(jtPrecioProducto.getText());
        Integer stock=Integer.parseInt(jtStock.getText());
        Integer stockMinimo= Integer.parseInt(jtStockMinimo.getText());
        Boolean estado= jcEstado.isSelected();
        
        
       if(productoActual==null){
           productoActual=new Producto(nombreProducto,descripcion,precioActual,stock,estado,stockMinimo);
           
           producData.guardarProducto(productoActual);
       }else{
           productoActual.setNombreProducto(nombreProducto);
           productoActual.setDescripcion(descripcion);
           productoActual.setPrecioActual(precioActual);
           productoActual.setStock(stock);
           productoActual.setStockMinimo(stockMinimo);
           
           producData.modificarProducto(productoActual);
       }
           
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
       if(productoActual!=null){
           producData.eliminarProductoId(productoActual.getIdProducto());
           productoActual=null;
           limpiarCampos();
       }else{
           JOptionPane.showMessageDialog(this, "No hay un producto seleccionado");
       }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
            dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcEstado;
    private javax.swing.JLabel jlRegistroProductos;
    private javax.swing.JTextField jtCodigoProducto;
    private javax.swing.JTextField jtDescripcionProducto;
    private javax.swing.JTextField jtNombreProducto;
    private javax.swing.JTextField jtPrecioProducto;
    private javax.swing.JTextField jtStock;
    private javax.swing.JTextField jtStockMinimo;
    // End of variables declaration//GEN-END:variables
}
